
name: 'snowflake_dbt'
version: '1.0.0'
config-version: 2

profile: 'snowflake_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  default_string: 'N/A'

seeds:
  +schema: public

models:
  snowflake_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      warehouse:
        +schema: warehouse
      reporting:
        +schema: reporting